export const categories = [
  {
    name: 'Shopping & Retail',
    subCategories: [
      'Jewelry',
      'Watches',
      'Fashion',
      'Shoes',
      'Bags',
      'Furniture',
      'Home Decor',
      'Electronics',
      'Mobile Shop',
      'Computer Store',
      'Gaming',
      'Toys',
      'Flowers',
      'Gifts',
      'Vape Shop',
      'Kiosk',
      'Supermarket',
      'Pet Shop',
      'Sports Store',
      'Optician',
      'Perfume Store',
      'Adult Store',
      'Cannabis Shop',
      'Supplements',
      'Luxury Goods',
      'Vending Machine',
    ],
  },

  {
    name: 'Food & Drink',
    subCategories: [
      'Restaurant',
      'Cafe',
      'Bakery',
      'Bar',
      'Fast Food',
      'Take Away',
      'Delivery',
      'Ice Cream',
      'Food Truck',
      'Catering',
      'Winery',
    ],
  },

  {
    name: 'Beauty & Health',
    subCategories: [
      'Hair Salon',
      'Cosmetic',
      'Nail Salon',
      'Spa & Wellness',
      'Massage',
      'Fitness',
      'Yoga & Pilates',
      'Therapy',
      'Tattoo Studio',
      'Beauty Clinic',
      'Dental Clinic',
      'Doctor',
      'Pharmacy',
      'Physiotherapy',
      'Chiropractic',
      'Nutrition Coach',
    ],
  },

  {
    name: 'Home Services',
    subCategories: [
      'Cleaning',
      'Moving',
      'Painting',
      'Plumbing',
      'Electrical',
      'Gardening',
      'Pest Control',
      'Flooring',
      'Roofing',
      'Interior Design',
      'Smart Home',
      'Renovation',
      'Kitchen Studio',
      'Carpenter',
      'Glass Service',
      'Solar',
      'HVAC',
      'Facility Service',
      'Security Systems',
    ],
  },

  {
    name: 'Construction & Real Estate',
    subCategories: [
      'Architect',
      'Construction Company',
      'Real Estate Agency',
      'Property Management',
      'Building Management',
      'Engineering',
      'Surveying',
      'Interior Architecture',
      'Real Estate Investment',
      'Coworking',
      'Commercial Property',
    ],
  },

  {
    name: 'Automotive & Mobility',
    subCategories: [
      'Garage',
      'Car Dealer',
      'Car Wash',
      'Car Rental',
      'Taxi',
      'Chauffeur',
      'Tuning',
      'Tire Service',
      'EV Charging',
      'Motorcycle',
      'Bicycle Shop',
      'Scooter',
      'Transport',
      'Logistics',
      'Courier',
      'Moving Transport',
      'Truck Service',
    ],
  },

  {
    name: 'Professional Services',
    subCategories: [
      'Insurance',
      'Accounting',
      'Lawyer',
      'Consulting',
      'Marketing Agency',
      'Web Agency',
      'Photographer',
      'Videographer',
      'Printing',
      'Recruiting',
      'Job Center',
      'Coaching',
      'Translation',
      'IT Support',
      'Software Company',
      'Telecom',
      'Security Service',
      'Bank',
      'Crypto Service',
      'Investment',
      'Mortgage',
      'Tax Advisor',
      'Notary',
      'Debt Consulting',
      'SaaS',
      'AI Company',
      'App Developer',
      'Hosting',
      'Cyber Security',
      'E-Commerce Service',
      'POS Systems',
    ],
  },

  {
    name: 'Entertainment & Leisure',
    subCategories: [
      'Lounge',
      'Cinema',
      'Bowling',
      'Escape Room',
      'Arcade',
      'Casino',
      'Event Location',
      'Nightclub',
      'Concert Venue',
      'Gaming Lounge',
      'VR Experience',
      'Theme Park',
      'Museum',
      'Zoo',
      'Swimming Pool',
      'Kids Playground',
    ],
  },

  {
    name: 'Travel & Hospitality',
    subCategories: [
      'Hotel',
      'Resort',
      'Airbnb',
      'Travel Agency',
      'Airline',
      'Cruise',
      'Ski Resort',
      'Camping',
      'Tour Guide',
      'Wellness Resort',
      'Hostel',
    ],
  },

  {
    name: 'Education & Community',
    subCategories: [
      'School',
      'Language School',
      'Driving School',
      'Tutor',
      'Academy',
      'University',
      'Childcare',
      'NGO',
      'Religious Center',
      'Club Association',
      'Community Center',
    ],
  },
] as const

export type Category = (typeof categories)[number]['name']
export type SubCategory =
  (typeof categories)[number]['subCategories'][number]