export const categories = [
  {
    name: 'Shopping',
    subCategories: [
      'Schmuck',
      'Uhren',
      'Mode',
      'Schuhe',
      'Taschen',
      'Möbel',
      'Wohndekoration',
      'Elektronik',
      'Handyshop',
      'Computerladen',
      'Gaming',
      'Spielwaren',
      'Blumen',
      'Geschenke',
      'Vape Shop',
      'Kiosk',
      'Supermarkt',
      'Tierbedarf',
      'Sportgeschäft',
      'Optiker',
      'Parfümerie',
      'Adult Shop',
      'Cannabis Shop',
      'Supplemente',
      'Luxusartikel',
      'Verkaufsautomat',
      'Souvenir',
      'Buchhandlung',
    ],
  },

  {
    name: 'Gastronomie',
    subCategories: [
      'Restaurant',
      'Café',
      'Bäckerei',
      'Bar',
      'Fast Food',
      'Take Away',
      'Lieferdienst',
      'Eisdiele',
      'Food Truck',
      'Catering',
      'Weinbar',
      'Dessert',
      'Bubble Tea',
      'Coffee Shop',
    ],
  },

  {
    name: 'Beauty & Gesundheit',
    subCategories: [
      'Coiffeur',
      'Kosmetik',
      'Nagelstudio',
      'Spa & Wellness',
      'Massage',
      'Fitness',
      'Yoga & Pilates',
      'Therapie',
      'Tattoo Studio',
      'Beauty Klinik',
      'Zahnklinik',
      'Arzt',
      'Apotheke',
      'Physiotherapie',
      'Chiropraktik',
      'Ernährungsberatung',
    ],
  },

  {
  name: 'Haus & Handwerk',
  subCategories: [
    'Reinigung',
    'Umzugstransport',
    'Entsorgung',
    'Entrümpelung',
    'Malerei',
    'Maurerarbeiten',
    'Trockenbau',
    'Gipser',
    'Fassadenbau',
    'Plattenleger',
    'Bodenleger',
    'Abbruch',
    'Gerüstbau',
    'Sanitär',
    'Elektrik',
    'Gartenbau',
    'Schädlingsbekämpfung',
    'Bodenbeläge',
    'Dachdecker',
    'Innendesign',
    'Smart Home',
    'Renovation',
    'Küchenstudio',
    'Schreinerei',
    'Glasservice',
    'Solar',
    'Klima & Lüftung',
    'Facility Service',
    'Sicherheitssysteme',
  ],
},

  {
    name: 'Bau & Immobilien',
    subCategories: [
      'Architekt',
      'Baufirma',
      'Immobilienagentur',
      'Liegenschaftsverwaltung',
      'Gebäudeverwaltung',
      'Ingenieur',
      'Vermessung',
      'Innenarchitektur',
      'Immobilieninvestment',
      'Coworking',
      'Gewerbeimmobilien',
    ],
  },

  {
    name: 'Auto & Mobilität',
    subCategories: [
      'Garage',
      'Autohandel',
      'Autowaschanlage',
      'Autovermietung',
      'Taxi',
      'Chauffeur Service',
      'Tuning',
      'Pneuservice',
      'E-Ladestation',
      'Motorrad',
      'Velogeschäft',
      'Scooter',
      'Transport',
      'Logistik',
      'Kurierdienst',
      'Umzugstransport',
      'Truck Service',
      'Entsorgung',
      'Entrümpelung',
      'Autotransport',
      'Transportervermietung',
    ],
  },

  {
    name: 'Dienstleistungen',
    subCategories: [
      'Versicherung',
      'Treuhand',
      'Anwalt',
      'Beratung',
      'Marketing Agentur',
      'Webagentur',
      'Fotograf',
      'Videograf',
      'Druckerei',
      'Recruiting',
      'Job Center',
      'Coaching',
      'Übersetzung',
      'IT Support',
      'Softwarefirma',
      'Telekommunikation',
      'Sicherheitsdienst',
      'Bank',
      'Krypto Service',
      'Investment',
      'Hypothek',
      'Steuerberatung',
      'Notariat',
      'Schuldenberatung',
      'SaaS',
      'KI Firma',
      'App Entwickler',
      'Hosting',
      'Cyber Security',
      'E-Commerce Service',
      'POS Systeme',
    ],
  },

  {
    name: 'Freizeit & Unterhaltung',
    subCategories: [
      'Lounge',
      'Kino',
      'Theater',
      'Bowling',
      'Escape Room',
      'Arcade',
      'Casino',
      'Eventlocation',
      'Nightclub',
      'Konzerthalle',
      'Gaming Lounge',
      'VR Experience',
      'Freizeitpark',
      'Museum',
      'Zoo',
      'Schwimmbad',
      'Kinderspielplatz',
      'Sehenswürdigkeit',
      'Aussichtspunkt',
      'Schloss',
      'Historischer Ort',
      'Touristenattraktion',
      'Photo Spot',
      'Bootstour',
      'Observation Deck',
      'Park',
      'See Attraktion',
    ],
  },

  {
    name: 'Reisen & Hotels',
    subCategories: [
      'Hotel',
      'Resort',
      'Airbnb',
      'Reisebüro',
      'Fluggesellschaft',
      'Kreuzfahrt',
      'Skigebiet',
      'Camping',
      'Tour Guide',
      'Wellness Resort',
      'Hostel',
    ],
  },

  {
    name: 'Bildung & Community',
    subCategories: [
      'Schule',
      'Sprachschule',
      'Fahrschule',
      'Nachhilfe',
      'Akademie',
      'Universität',
      'Kinderbetreuung',
      'NGO',
      'Religious Center',
      'Verein',
      'Community Center',
      'Musikschule',
    ],
  },
] as const

export type Category = (typeof categories)[number]['name']

export type SubCategory =
  (typeof categories)[number]['subCategories'][number]