export type JourneyType =
  | 'shopping'
  | 'food'
  | 'selfcare'
  | 'project'
  | 'home'
  | 'mobility'
  | 'convenience'
  | 'business'
  | 'leisure'
  | 'travel'
  | 'nightlife'
  | 'education'

export const journeyMap: Record<string, JourneyType> = {
  Schmuck: 'shopping',
  Uhren: 'shopping',
  Mode: 'shopping',
  Schuhe: 'shopping',
  Taschen: 'shopping',
  Möbel: 'home',
  Wohndekoration: 'home',
  Elektronik: 'shopping',
  Handyshop: 'shopping',
  Computerladen: 'shopping',
  Gaming: 'leisure',
  Spielwaren: 'shopping',
  Blumen: 'shopping',
  Geschenke: 'shopping',
  Supermarkt: 'shopping',
  Tierbedarf: 'shopping',
  Sportgeschäft: 'shopping',
  Optiker: 'shopping',
  Parfümerie: 'shopping',
  Supplemente: 'selfcare',
  Luxusartikel: 'shopping',
  Souvenir: 'shopping',
  Buchhandlung: 'shopping',

  Tankstelle: 'convenience',
  Kiosk: 'convenience',
  '24h Shop': 'convenience',
  Verkaufsautomat: 'convenience',

  Restaurant: 'food',
  Café: 'leisure',
  Bäckerei: 'leisure',
  Bar: 'nightlife',
  'Fast Food': 'food',
  'Take Away': 'food',
  Lieferdienst: 'food',
  Eisdiele: 'leisure',
  'Food Truck': 'food',
  Catering: 'business',
  Weinbar: 'nightlife',
  Dessert: 'leisure',
  'Bubble Tea': 'leisure',
  'Coffee Shop': 'leisure',

  Coiffeur: 'selfcare',
  Kosmetik: 'selfcare',
  Nagelstudio: 'selfcare',
  'Spa & Wellness': 'selfcare',
  Massage: 'selfcare',
  Fitness: 'selfcare',
  'Yoga & Pilates': 'selfcare',
  Therapie: 'selfcare',
  'Tattoo Studio': 'selfcare',
  'Beauty Klinik': 'selfcare',
  Zahnklinik: 'selfcare',
  Arzt: 'selfcare',
  Apotheke: 'selfcare',
  Physiotherapie: 'selfcare',
  Chiropraktik: 'selfcare',
  Ernährungsberatung: 'selfcare',

  Reinigung: 'project',
  Umzugstransport: 'home',
  Entsorgung: 'project',
  Entrümpelung: 'project',
  Malerei: 'home',
  Maurerarbeiten: 'project',
  Trockenbau: 'project',
  Gipser: 'project',
  Fassadenbau: 'project',
  Plattenleger: 'home',
  Bodenleger: 'home',
  Abbruch: 'project',
  Gerüstbau: 'project',
  Sanitär: 'home',
  Elektrik: 'home',
  Gartenbau: 'home',
  Schädlingsbekämpfung: 'home',
  Bodenbeläge: 'home',
  Dachdecker: 'home',
  Innendesign: 'home',
  'Smart Home': 'home',
  Renovation: 'home',
  Küchenstudio: 'home',
  Schreinerei: 'home',
  Glasservice: 'home',
  Solar: 'home',
  'Klima & Lüftung': 'home',
  'Facility Service': 'project',
  Sicherheitssysteme: 'home',

  Architekt: 'project',
  Baufirma: 'project',
  Immobilienagentur: 'home',
  Liegenschaftsverwaltung: 'project',
  Gebäudeverwaltung: 'project',
  Ingenieur: 'project',
  Vermessung: 'project',
  Innenarchitektur: 'home',
  Immobilieninvestment: 'business',
  Coworking: 'business',
  Gewerbeimmobilien: 'business',

  Garage: 'mobility',
  Autohandel: 'mobility',
  Autowaschanlage: 'mobility',
  Autovermietung: 'mobility',
  Taxi: 'mobility',
  'Chauffeur Service': 'mobility',
  Tuning: 'mobility',
  Pneuservice: 'mobility',
  'E-Ladestation': 'mobility',
  Motorrad: 'mobility',
  Velogeschäft: 'mobility',
  Scooter: 'mobility',
  Transport: 'mobility',
  Logistik: 'business',
  Kurierdienst: 'business',
  Autotransport: 'mobility',
  Transportervermietung: 'mobility',

  Versicherung: 'business',
  Treuhand: 'business',
  Anwalt: 'business',
  Beratung: 'business',
  'Marketing Agentur': 'business',
  Webagentur: 'business',
  Fotograf: 'business',
  Videograf: 'business',
  Druckerei: 'business',
  Recruiting: 'business',
  'Job Center': 'business',
  Coaching: 'education',
  Übersetzung: 'business',
  'IT Support': 'business',
  Softwarefirma: 'business',
  Telekommunikation: 'business',
  Sicherheitsdienst: 'business',
  Bank: 'business',
  'Krypto Service': 'business',
  Investment: 'business',
  Hypothek: 'business',
  Steuerberatung: 'business',
  Notariat: 'business',
  Schuldenberatung: 'business',
  SaaS: 'business',
  'KI Firma': 'business',
  'App Entwickler': 'business',
  Hosting: 'business',
  'Cyber Security': 'business',
  'E-Commerce Service': 'business',
  'POS Systeme': 'business',

  Lounge: 'nightlife',
  Kino: 'leisure',
  Theater: 'leisure',
  Bowling: 'leisure',
  'Escape Room': 'leisure',
  Arcade: 'leisure',
  Casino: 'nightlife',
  Eventlocation: 'leisure',
  Nightclub: 'nightlife',
  Konzerthalle: 'nightlife',
  'Gaming Lounge': 'leisure',
  'VR Experience': 'leisure',
  Freizeitpark: 'leisure',
  Museum: 'leisure',
  Zoo: 'leisure',
  Schwimmbad: 'leisure',
  Kinderspielplatz: 'leisure',
  Sehenswürdigkeit: 'leisure',
  Aussichtspunkt: 'leisure',
  Schloss: 'leisure',
  'Historischer Ort': 'leisure',
  Touristenattraktion: 'leisure',
  'Photo Spot': 'leisure',
  Bootstour: 'leisure',
  'Observation Deck': 'leisure',
  Park: 'leisure',
  'See Attraktion': 'leisure',

  Hotel: 'travel',
  Resort: 'travel',
  Airbnb: 'travel',
  Reisebüro: 'travel',
  Fluggesellschaft: 'travel',
  Kreuzfahrt: 'travel',
  Skigebiet: 'travel',
  Camping: 'travel',
  'Tour Guide': 'travel',
  'Wellness Resort': 'travel',
  Hostel: 'travel',

  Schule: 'education',
  Sprachschule: 'education',
  Fahrschule: 'education',
  Nachhilfe: 'education',
  Akademie: 'education',
  Universität: 'education',
  Kinderbetreuung: 'education',
  NGO: 'education',
  'Religious Center': 'leisure',
  Verein: 'leisure',
  'Community Center': 'leisure',
  Musikschule: 'education',
}

export const instantRelevanceMap: Record<JourneyType, Record<string, number>> = {
  shopping: {
    Café: 5,
    Restaurant: 4,
    Bäckerei: 4,
    Eisdiele: 4,
    Dessert: 4,
    'Bubble Tea': 4,
    'Coffee Shop': 4,
    Blumen: 3,
    Geschenke: 3,
    Kino: 3,
    Bar: 3,
    Lounge: 3,
    Parfümerie: 3,
    Schmuck: 3,
    Mode: 3,
  },

  food: {
    Dessert: 5,
    Eisdiele: 5,
    Café: 5,
    'Bubble Tea': 5,
    'Coffee Shop': 5,
    Bäckerei: 4,
    Bar: 4,
    Lounge: 4,
    Nightclub: 4,
    Kino: 4,
    Bowling: 3,
    Eventlocation: 3,
    Taxi: 3,
    Kiosk: 3,
    '24h Shop': 3,
    Verkaufsautomat: 3,
    Fitness: 2,
  },

  selfcare: {
    Café: 5,
    Restaurant: 5,
    Dessert: 5,
    Eisdiele: 5,
    'Bubble Tea': 5,
    'Coffee Shop': 5,
    Mode: 5,
    Parfümerie: 5,
    Schmuck: 4,
    Uhren: 4,
    Taschen: 4,
    Schuhe: 4,
    Bar: 4,
    Lounge: 4,
    Nightclub: 4,
    Bäckerei: 4,
    Blumen: 3,
    Geschenke: 3,
    Kino: 2,
    Bowling: 2,
    Eventlocation: 2,
    Kosmetik: 2,
    Nagelstudio: 2,
    Massage: 2,
    Fitness: 2,
    'Spa & Wellness': 2,
    Supplemente: 2,
  },

  project: {
    Reinigung: 5,
    Renovation: 5,
    Malerei: 5,
    Entsorgung: 5,
    Entrümpelung: 5,
    Umzugstransport: 5,
    Transport: 4,
    Möbel: 4,
    Küchenstudio: 4,
    Schreinerei: 4,
    Sanitär: 4,
    Elektrik: 4,
    Gartenbau: 4,
    Bodenbeläge: 4,
    Bodenleger: 4,
    Plattenleger: 4,
    Dachdecker: 4,
    Glasservice: 3,
    Innendesign: 3,
    Liegenschaftsverwaltung: 3,
    Gebäudeverwaltung: 3,
    Immobilienagentur: 3,
    Architekt: 3,
    Baufirma: 3,
  },

  home: {
    Reinigung: 5,
    Renovation: 5,
    Möbel: 5,
    Wohndekoration: 5,
    Malerei: 4,
    Umzugstransport: 4,
    Entsorgung: 4,
    Entrümpelung: 4,
    Gartenbau: 4,
    Küchenstudio: 4,
    Schreinerei: 4,
    Sanitär: 3,
    Elektrik: 3,
    Bodenleger: 3,
    Bodenbeläge: 3,
    Plattenleger: 3,
    Innendesign: 3,
    'Smart Home': 3,
    Sicherheitssysteme: 5,
    Solar: 3,
    'Klima & Lüftung': 3,
    Elektronik: 2,
    Liegenschaftsverwaltung: 2,
  },

  convenience: {
    'Fast Food': 5,
    'Take Away': 5,
    Restaurant: 4,
    Café: 4,
    'Coffee Shop': 4,
    'Bubble Tea': 4,
    Dessert: 4,
    Eisdiele: 4,
    Bäckerei: 4,
    Bar: 4,
    Lounge: 4,
    Nightclub: 3,
    Autowaschanlage: 3,
    Taxi: 3,
    Verkaufsautomat: 3,
    Kiosk: 3,
    '24h Shop': 3,
  },

  mobility: {
    Autowaschanlage: 5,
    Pneuservice: 5,
    Garage: 4,
    'E-Ladestation': 4,
    Tankstelle: 4,
    Kiosk: 3,
    '24h Shop': 3,
    Café: 3,
    'Coffee Shop': 3,
    'Fast Food': 3,
    'Take Away': 3,
    Taxi: 3,
    Transportervermietung: 3,
    Autovermietung: 3,
    Autohandel: 2,
    Tuning: 2,
    Motorrad: 2,
    Velogeschäft: 2,
  },

  business: {
    Coworking: 5,
    Druckerei: 5,
    'IT Support': 4,
    Telekommunikation: 4,
    Treuhand: 4,
    Beratung: 4,
    Webagentur: 4,
    'Marketing Agentur': 4,
    Softwarefirma: 4,
    Café: 4,
    'Coffee Shop': 4,
    Reinigung: 3,
    Liegenschaftsverwaltung: 3,
    Gebäudeverwaltung: 3,
    Versicherung: 3,
    Bank: 3,
    Steuerberatung: 3,
    Notariat: 3,
    Fotograf: 3,
    Videograf: 3,
    Recruiting: 3,
    'Job Center': 3,
    Übersetzung: 3,
    'Cyber Security': 3,
    Hosting: 3,
    SaaS: 3,
    'KI Firma': 3,
    'App Entwickler': 3,
  },

  leisure: {
    Café: 5,
    Restaurant: 5,
    Dessert: 5,
    Eisdiele: 5,
    'Bubble Tea': 5,
    'Coffee Shop': 5,
    Bäckerei: 4,
    Bar: 4,
    Lounge: 4,
    Kino: 4,
    Bowling: 4,
    'Escape Room': 4,
    Arcade: 4,
    Eventlocation: 4,
    Nightclub: 3,
    Geschenke: 4,
    Souvenir: 4,
    Hotel: 3,
    Taxi: 3,
    Museum: 3,
    Park: 3,
    Schwimmbad: 3,
  },

  travel: {
    Restaurant: 5,
    Café: 5,
    Taxi: 5,
    Hotel: 5,
    'Tour Guide': 5,
    Bar: 4,
    Lounge: 4,
    Museum: 4,
    Sehenswürdigkeit: 4,
    Aussichtspunkt: 4,
    'See Attraktion': 4,
    Bootstour: 4,
    Souvenir: 4,
    'Photo Spot': 4,
    Park: 3,
    'Spa & Wellness': 3,
    Resort: 3,
    Reisebüro: 3,
    Fluggesellschaft: 3,
  },

  nightlife: {
    Taxi: 5,
    'Fast Food': 5,
    'Take Away': 5,
    Kiosk: 4,
    '24h Shop': 4,
    Verkaufsautomat: 4,
    Restaurant: 4,
    Hotel: 4,
    Café: 3,
    'Coffee Shop': 3,
    Bäckerei: 3,
    Tankstelle: 3,
    Autovermietung: 2,
    'Chauffeur Service': 4,
  },

  education: {
    Buchhandlung: 5,
    Café: 4,
    Bäckerei: 4,
    'Coffee Shop': 4,
    Druckerei: 4,
    Coworking: 3,
    'Bubble Tea': 3,
    Nachhilfe: 3,
    Sprachschule: 3,
    Musikschule: 3,
    Coaching: 3,
  },
}

export function getJourneyType(subCategory: string | null | undefined): JourneyType | null {
  if (!subCategory) return null
  return journeyMap[subCategory] ?? null
}

export function getInstantRelevanceScore(
  sourceSubCategory: string | null | undefined,
  targetSubCategory: string | null | undefined
): number {
  if (!sourceSubCategory || !targetSubCategory) return 1

  const journeyType = getJourneyType(sourceSubCategory)
  if (!journeyType) return 1

  const relevance = instantRelevanceMap[journeyType]
  return relevance[targetSubCategory] ?? 0
}